version: '3.8'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: client
    ports:
      - "5000:5000"
    networks:
      - distributed_net
  
  master:
    build:
      context: .
      dockerfile: Dockerfile.manager
    container_name: master
    ports:
      - "5001:5001"
    networks:
      - distributed_net

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: worker
    ports:
      - "5002:5002"
    networks:
      - distributed_net


networks:
  distributed_net:
    driver: bridge
