FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

COPY ../*.sln ./
COPY ../DistributedFileSystem.Client/DistributedFileSystem.Client.csproj ./DistributedFileSystem.Client/

RUN dotnet restore

RUN dotnet publish DistributedFileSystem.Client/DistributedFileSystem.Client.csproj -c Release -o /app/publish


FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app

COPY --from=build /app/publish /app

ENTRYPOINT ["dotnet", "DistributedFileSystem.Client.dll"]
EXPOSE 80
