global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'alertmanager:9093'

scrape_configs:
  - job_name: 'scrape_master:5001'
    scrape_interval: 15s
    scheme: https
    static_configs:
      - targets: ['master:5001']
    tls_config:
      insecure_skip_verify: true

  - job_name: 'scrape_worker:5002'
    scrape_interval: 15s
    scheme: https
    static_configs:
      - targets: ['worker:5002']
    tls_config:
      insecure_skip_verify: true
