apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-master-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-master
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-master
    spec:
      containers:
        - name: master
          image: "{{ .Values.master.image.repository }}:{{ .Values.master.image.tag }}"
          ports:
            - containerPort: {{ .Values.master.port }} 

