apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-master-service
spec:
  selector:
    app: {{ .Release.Name }}-master
  ports:
    - protocol: TCP
      port: {{ .Values.master.port }}
      targetPort: {{ .Values.master.port }}
  type: ClusterIP

