apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'master_node'
        scheme: https
        static_configs:
          - targets: ['master-service:5001']
        tls_config:
          insecure_skip_verify: true
      
      - job_name: 'worker_node'
        scheme: https
        static_configs:
          - targets: ['worker-service:5002']
        tls_config:
          insecure_skip_verify: true