global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'scrape_https://localhost:5001'
    scrape_interval: 15s
    scheme: https
    static_configs:
      - targets: ['localhost:5001']
    tls_config:
      insecure_skip_verify: true

  - job_name: 'scrape_https://localhost:5002'
    scrape_interval: 15s
    scheme: https
    static_configs:
      - targets: ['localhost:5002']
    tls_config:
      insecure_skip_verify: true
