global:
  scrape_interval: 15s

# Master Node
scrape_configs:
  - job_name: 'scrape_https://localhost:5001'
      scrape_interval: 15s
      static_configs:
        - targets: ['https://localhost:5001']

  - job_name: 'scrape_https://localhost:5002'
    scrape_interval: 15s
    static_configs:
      - targets: ['https://localhost:5002']
