apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-prometheus-service
spec:
  selector:
    app: {{ .Release.Name }}-prometheus
  ports:
    - port: 9090
      targetPort: 9090
  type: ClusterIP

