apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-client-service
spec:
  selector:
    app: {{ .Release.Name }}-client
  ports:
    - protocol: TCP
      port: {{ .Values.client.port }}
      targetPort: {{ .Values.client.port }}
  type: LoadBalancer

