apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-alertmanager-config
  namespace: default
  labels:
    app: {{ .Release.Name }}-alertmanager
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      receiver: 'email-receiver'

    receivers:
      - name: 'email-receiver'
        email_configs:
          - to: "{{ .Values.alertmanager.smtp.to }}"
            from: "{{ .Values.alertmanager.smtp.from }}"
            smarthost: "{{ .Values.alertmanager.smtp.host }}:{{ .Values.alertmanager.smtp.port }}"
            auth_username: "{{ .Values.alertmanager.smtp.username }}"
            auth_password: "{{ .Values.alertmanager.smtp.password }}"
            send_resolved: true

