apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-alertmanager
  namespace: default
  labels:
    app: {{ .Release.Name }}-alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-alertmanager
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-alertmanager
    spec:
      containers:
        - name: alertmanager
          image: "{{ .Values.alertmanager.image.repository }}:{{ .Values.alertmanager.image.tag }}"
          ports:
            - containerPort: 9093
          volumeMounts:
            - mountPath: /etc/alertmanager/alertmanager.yml
              name: alertmanager-config
              subPath: alertmanager.yml
              readOnly: true
          env:
            - name: SMTP_TO
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-alertmanager-secrets
                  key: SMTP_TO
            - name: SMTP_FROM
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-alertmanager-secrets
                  key: SMTP_FROM
            - name: SMTP_SMARTHOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-alertmanager-secrets
                  key: SMTP_SMARTHOST
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-alertmanager-secrets
                  key: SMTP_USERNAME
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-alertmanager-secrets
                  key: SMTP_PASSWORD
      volumes:
        - name: alertmanager-config
          configMap:
            name: {{ .Release.Name }}-alertmanager-config

