apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-alertmanager
  namespace: default
spec:
  selector:
    app: {{ .Release.Name }}-alertmanager
  ports:
    - port: 9093
      targetPort: 9093
  type: ClusterIP

