apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-worker-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Release.Name }}-worker
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          ports:
            - containerPort: {{ .Values.worker.port }}

