apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-worker-service
spec:
  selector:
    app: {{ .Release.Name }}-worker
  ports:
    - protocol: TCP
      port: {{ .Values.worker.port }}
      targetPort: {{ .Values.worker.port }}
  type: ClusterIP

